# Generated by Django 3.2.25 on 2024-05-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longrunningtask',
            name='name',
        ),
        migrations.AddField(
            model_name='longrunningtask',
            name='location',
            field=models.CharField(default='http://127.0.0.1:8000/long_running_task/get-progress/{id}', max_length=100),
        ),
        migrations.AddField(
            model_name='longrunningtask',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='longrunningtask',
            name='result',
            field=models.CharField(default='http://127.0.0.1:8000/media/{location}', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='longrunningtask',
            name='status',
            field=models.CharField(default='INQUEUE', max_length=10),
        ),
        migrations.AlterField(
            model_name='longrunningtask',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
