# Generated by Django 3.2.25 on 2024-05-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_task', '0004_rename_longrunningtask_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskDBModel',
        ),
    ]
