# Generated by Django 3.2.25 on 2024-05-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_task', '0005_rename_task_taskdbmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDBModel',
        ),
    ]
