# Generated by Django 3.2.25 on 2024-05-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_task', '0009_rename_image_taskdbmodel_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdbmodel',
            name='image_name',
            field=models.CharField(default='null', max_length=256, null=True),
        ),
    ]
