# Generated by Django 3.2.25 on 2024-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_running_task', '0012_alter_taskdbmodel_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdbmodel',
            name='image_id',
            field=models.CharField(default='null', max_length=256, null=True),
        ),
    ]
