# Generated by Django 5.0.4 on 2024-04-21 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='value',
        ),
        migrations.AddField(
            model_name='image',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='file_path',
            field=models.CharField(default='./images', max_length=256),
        ),
        migrations.AddField(
            model_name='image',
            name='meta_height',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='image',
            name='meta_width',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(default='JPEG', max_length=128),
        ),
    ]
