# Generated by Django 5.0.4 on 2024-04-21 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_remove_image_value_image_createdat_image_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
