# Generated by Django 5.0.4 on 2024-04-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_rename_createdat_image_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mime_type',
            field=models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG')], default='image/jpeg', max_length=50),
        ),
    ]
