# Generated by Django 5.0.4 on 2024-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_alter_image_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='meta_size_byte',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
