# Generated by Django 5.0.4 on 2024-04-29 06:28


import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0006_rename_image_imagedbmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedbmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]